### ISSUE TITLE
为什么不搞个LICENSE文件啊

### ISSUE THREAD

**Issue by OrO-c** [buxia97/RuleUser#1]
![Screenshot_20240818215215](https://github.com/user-attachments/assets/4149b046-f6ba-41ee-872e-27b070ad3b13)

**Comment by buxia97** [comment]
好的，我会及时补充下

**Comment by OrO-c** [comment]
哦哦

**Comment by OrO-c** [comment]
而且这个也是要改的，因为没有写明是GPL2.0还是3.0，被人恶意使用很容易钻空子
